[project]
name = "pymyair"
version = "0.2.1"
requires-python = ">=3.8"
dynamic = ["description", "readme", "license", "authors", "keywords", "classifiers", "dependencies", "scripts"]

[build-system]
requires = ["setuptools>=70", "wheel"]
build-backend = "setuptools.build_meta"
