[project]
name = "pymyair"
version = "0.0.0"
requires-python = ">=3.8"

[tool.poetry]
name = "pymyair"
version = "0.0.0"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
